name: release
on:
  push:
    branches:
      - master

jobs:
  github:
    runs-on: ubuntu-24.04
    if: "contains(github.event.head_commit.message, 'chore: release')"
    steps:
      - run: sudo apt-get install -y libpango1.0-dev libgraphene-1.0-dev

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: dtolnay/rust-toolchain@stable

      - uses: MarcoIeni/release-plz-action@v0.5
        with:
          command: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true

      - uses: docker/setup-qemu-action@v3

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Find version tags
        id: get_tags
        run: |
          for tag in $(git tag --points-at HEAD); do
            echo "turbine=${tag##*-}" >>"$GITHUB_OUTPUT"
          done

      - uses: docker/build-push-action@v5
        if: ${{ steps.get_tags.outputs.turbine != '' }}
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: fossable/turbine:latest,fossable/turbine:${{ steps.get_tags.outputs.turbine }}

      - uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: fossable/turbine

