name: release
on:
  push:
    branches:
      - master

jobs:
  github:
    runs-on: ubuntu-24.04
    if: "contains(github.event.head_commit.message, 'chore: release')"
    steps:
      - run: sudo apt-get install -y libpango1.0-dev libgraphene-1.0-dev

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: dtolnay/rust-toolchain@stable

      - uses: MarcoIeni/release-plz-action@v0.5
        with:
          command: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

  linux:
    name: linux / ${{ matrix.target }}
    runs-on: ubuntu-latest
    needs: github
    strategy:
      fail-fast: false
      matrix:
        target:
          - aarch64-unknown-linux-gnu
          - aarch64-unknown-linux-musl
          - i686-unknown-linux-gnu
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target ${{ matrix.target }}

      - uses: actions/upload-artifact@v4
        with:
          name: turbine-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/turbine

      - name: Upload artifacts to release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
        run: |
          for tag in $(git tag --points-at HEAD); do
            if cp target/${{ matrix.target }}/release/turbine turbine_${{ matrix.target }}; then
              gh release upload "${tag##*-}" "turbine_${{ matrix.target }}"
            fi
          done

  docker:
    runs-on: ubuntu-latest
    needs: linux
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true

      - uses: docker/setup-qemu-action@v3

      - uses: docker/setup-buildx-action@v3

      - uses: actions/download-artifact@v4
        with:
          name: turbine-x86_64-unknown-linux-musl
          path: turbine/linux-amd64

      - uses: actions/download-artifact@v4
        with:
          name: turbine-aarch64-unknown-linux-musl
          path: turbine/linux-arm64

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Find version tags
        id: get_tags
        run: |
          for tag in $(git tag --points-at HEAD); do
            echo "turbine=${tag##*-}" >>"$GITHUB_OUTPUT"
          done

      - uses: docker/build-push-action@v5
        if: ${{ steps.get_tags.outputs.turbine != '' }}
        with:
          context: .
          platforms: linux/amd64 #,linux/arm64,linux/arm/v7
          push: true
          tags: fossable/turbine:latest,fossable/turbine:${{ steps.get_tags.outputs.turbine }}

      - uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: fossable/turbine

